### ISSUE TITLE
Requesting attachment of document

### ISSUE THREAD

**Issue by Warrior-Tobiramasenju** [Vishnu-Naruto/Whatsap_Development#4]
Dear Vishnu,

It would be great if the app is capable of attaching the documents as well. Kindly add this feature.

**Comment by Vishnu-Naruto** [comment]
Dear Tobi,
                Thanks for suggestion.this feature will add and let you know.

**Comment by Vishnu-Naruto** [comment]
Dear Tobi , 
                 Thanks For Your Valuable Suggestion This Feature is going to make our product great.
